# -*- coding: utf-8 -*-
"""SistemaBancarioDIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJX7ATla9mVdO1H1d3URC0hJbQv5KFT0

# Sistema Bancário Python - DIO
"""

menu = """

[d] Depositar
[s] Sacar
[e] Extrato
[q] Sair

=> """

saldo = 0
limite = 500
extrato = ""
numero_saques = 0
LIMITE_SAQUES = 3

while True:

    opcao = input(menu).strip().lower()

    if opcao == "d":
        try:
            valor = float(input("Informe o valor do depósito: ").strip())
            if valor > 0:
                saldo += valor
                extrato += f"Depósito: R$ {valor:.2f}\n"
                print(f"Depósito de R$ {valor:.2f} realizado com sucesso!")
            else:
                print("Operação falhou! O valor informado deve ser positivo.")
        except ValueError:
            print("Operação falhou! Valor inválido, por favor insira um número válido.")

    elif opcao == "s":
        try:
            valor = float(input("Informe o valor do saque: ").strip())
            if valor <= 0:
                print("Operação falhou! O valor informado deve ser positivo.")
            else:
                excedeu_saldo = valor > saldo
                excedeu_limite = valor > limite
                excedeu_saques = numero_saques >= LIMITE_SAQUES

                if excedeu_saldo:
                    print("Operação falhou! Você não tem saldo suficiente.")
                elif excedeu_limite:
                    print("Operação falhou! O valor do saque excede o limite.")
                elif excedeu_saques:
                    print("Operação falhou! Número máximo de saques excedido.")
                else:
                    saldo -= valor
                    extrato += f"Saque: R$ {valor:.2f}\n"
                    numero_saques += 1
                    print(f"Saque de R$ {valor:.2f} realizado com sucesso!")
        except ValueError:
            print("Operação falhou! Valor inválido, por favor insira um número válido.")

    elif opcao == "e":
        print("\n================ EXTRATO ================")
        print("Não foram realizadas movimentações." if not extrato else extrato)
        print(f"Saldo atual: R$ {saldo:.2f}")
        print("==========================================")

    elif opcao == "q":
        print("Obrigado por usar nosso sistema bancário. Até logo!")
        break

    else:
        print("Operação inválida, por favor selecione novamente a operação desejada.")